# Project 9 -- Taylor Saunders

**TA Help:** 
na
    
**Collaboration:** 
na

## Question 1

In [1]:
import pandas as pd

In [2]:
myDF = pd.read_csv("/anvil/projects/tdm/data/whin/weather.csv")

In [3]:
myDF.head

<bound method NDFrame.head of         station_id   latitude  longitude              name  \
0                1  40.938940 -86.474180   WHIN001-PULA001
1                1  40.938940 -86.474180   WHIN001-PULA001
2                1  40.938940 -86.474180   WHIN001-PULA001
3                1  40.938940 -86.474180   WHIN001-PULA001
4                1  40.938940 -86.474180   WHIN001-PULA001
...            ...        ...        ...               ...
999995         171  40.296799 -87.390285  WHIN038E-WARR004
999996         171  40.296799 -87.390285  WHIN038E-WARR004
999997         171  40.296799 -87.390285  WHIN038E-WARR004
999998         171  40.296799 -87.390285  WHIN038E-WARR004
999999         171  40.296799 -87.390285  WHIN038E-WARR004

            observation_time  temperature  temperature_high  temperature_low  \
0       2019-07-10T04:00:00Z         70.0              71.0             70.0
1       2019-07-10T04:15:00Z         69.0              70.0             69.0
2       2019-07-11T04:00:00Z         76.0              77.0             76.0
3       2019-07-11T04:15:00Z         76.0              76.0             76.0
4       2019-07-11T04:30:00Z         76.0              76.0             76.0
...                      ...          ...               ...              ...
999995  2021-07-10T06:30:00Z         64.0              64.0             64.0
999996  2021-07-10T06:45:00Z         64.0              64.0             64.0
999997  2021-07-10T07:00:00Z         64.0              64.0             64.0
999998  2021-07-10T07:15:00Z         64.0              64.0             64.0
999999  2021-07-10T07:30:00Z         64.0              64.0             63.0

        humidity  solar_radiation  ...  wind_gust_direction_degrees  pressure  \
0           83.0              NaN  ...                        247.5    30.050
1           84.0              NaN  ...                        247.5    30.040
2           76.0              NaN  ...                        202.5    29.890
3           77.0              NaN  ...                        202.5    29.880
4           77.0              NaN  ...                        202.5    29.880
...          ...              ...  ...                          ...       ...
999995      91.0              0.0  ...                          NaN    30.015
999996      90.0              0.0  ...                         90.0    30.017
999997      91.0              0.0  ...                         67.5    30.016
999998      91.0              0.0  ...                         67.5    30.010
999999      91.0              0.0  ...                         67.5    29.996

        soil_temp_1  soil_temp_2  soil_temp_3  soil_temp_4  soil_moist_1  \
0              77.0         78.0         76.0         74.0          24.0
1              76.0         78.0         76.0         74.0          24.0
2              80.0         80.0         78.0         75.0          31.0
3              80.0         80.0         78.0         75.0          31.0
4              80.0         80.0         78.0         75.0          32.0
...             ...          ...          ...          ...           ...
999995          NaN          NaN          NaN          NaN           NaN
999996          NaN          NaN          NaN          NaN           NaN
999997          NaN          NaN          NaN          NaN           NaN
999998          NaN          NaN          NaN          NaN           NaN
999999          NaN          NaN          NaN          NaN           NaN

        soil_moist_2  soil_moist_3  soil_moist_4
0               24.0          10.0           9.0
1               25.0          10.0           9.0
2               30.0          12.0          10.0
3               31.0          12.0          10.0
4               31.0          12.0          10.0
...              ...           ...           ...
999995           NaN           NaN           NaN
999996           NaN           NaN           NaN
999997           NaN           NaN           NaN
999998           NaN           NaN           NaN
999999           NaN           NaN           NaN

[1000000 rows x 26 columns]>

### Use the method value_counts() to get the number of records for each station.

In [4]:
myDF.value_counts()

station_id  latitude   longitude   name              observation_time      temperature  temperature_high  temperature_low  humidity  solar_radiation  solar_radiation_high  rain  rain_inches_last_hour  wind_speed_mph  wind_direction_degrees  wind_gust_speed_mph  wind_gust_direction_degrees  pressure  soil_temp_1  soil_temp_2  soil_temp_3  soil_temp_4  soil_moist_1  soil_moist_2  soil_moist_3  soil_moist_4
1           40.938940  -86.474180  WHIN001-PULA001   2019-11-21T19:15:00Z  52.0         52.0              52.0             94.0      31.0             42.0                  0.0   0.0                    19.0            225.0                   29.0                 225.0                        29.805    46.0         44.0         44.0         44.0         7.0           14.0          11.0          9.0             1
156         40.514320  -86.458560  WHIN065-CARR011   2020-12-18T19:00:00Z  33.0         33.0              33.0             77.0      377.0            461.0                 0.0   0.0                    11.0            157.5                   15.0                 135.0                        29.594    34.0         36.0         38.0         40.0         6.0           6.0           8.0           7.0             1
                                                     2020-12-18T16:45:00Z  30.0         30.0              30.0             81.0      449.0            468.0                 0.0   0.0                    7.0             135.0                   11.0                 157.5                        29.645    34.0         36.0         38.0         40.0         6.0           6.0           8.0           7.0             1
                                                     2020-12-18T17:00:00Z  30.0         30.0              30.0             80.0      426.0            454.0                 0.0   0.0                    9.0             157.5                   12.0                 157.5                        29.632    34.0         36.0         38.0         40.0         6.0           6.0           8.0           7.0             1
                                                     2020-12-18T17:15:00Z  31.0         31.0              30.0             79.0      398.0            436.0                 0.0   0.0                    9.0             157.5                   14.0                 157.5                        29.629    34.0         36.0         38.0         40.0         6.0           6.0           8.0           7.0             1
                                                                                                                                                                                                                                                                                                                                                                                                                          ..
146         40.431340  -86.534640  WHIN056-CLIN004   2020-04-12T00:15:00Z  57.0         57.0              57.0             34.0      8.0              14.0                  0.0   0.0                    8.0             202.5                   11.0                 180.0                        29.045    54.0         53.0         49.0         48.0         166.0         200.0         200.0         44.0            1
                                                     2020-04-12T00:30:00Z  57.0         57.0              57.0             37.0      0.0              0.0                   0.0   0.0                    7.0             202.5                   10.0                 180.0                        29.046    54.0         53.0         49.0         48.0         166.0         200.0         200.0         43.0            1
                                                     2020-04-12T00:45:00Z  56.0         57.0              56.0             39.0      0.0              0.0                   0.0   0.0                    8.0             180.0                   12.0                 180.0                        29.036    54.0         53.0         50.0         48.0         166.0         200.0         200.0         43.0            1
                                                     2020-04-12T01:00:00Z  56.0         56.0              56.0             39.0      0.0              0.0                   0.0   0.0                    9.0             180.0                   14.0                 157.5                        29.023    54.0         53.0         50.0         48.0         165.0         200.0         200.0         42.0            1
179         40.386114  -87.101296  WHIN012E-WARR002  2021-03-12T05:00:00Z  42.0         42.0              41.0             78.0      0.0              0.0                   0.0   0.0                    1.0             337.5                   4.0                  337.5                        30.295    48.0         48.0         47.0         46.0         7.0           7.0           4.0           2.0             1
Name: count, Length: 767725, dtype: int64

### Use the method groupby() to get the number of records for each station.

In [5]:
groupDF = myDF.groupby('station_id')
groupDF.first()

,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,...,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
station_id,,,,,,,,,,,,,,,,,,,,,
1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,31.0,42.0,...,247.5,30.050,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0
20,40.270957,-87.148604,WHIN020-FOUN001,2019-08-21T15:00:00Z,74.0,74.0,74.0,84.0,338.0,388.0,...,202.5,30.020,78.0,78.0,76.0,75.0,0.0,0.0,0.0,0.0
142,40.104830,-86.866190,WHIN052-MONT004,2020-04-09T16:30:00Z,48.0,48.0,48.0,43.0,906.0,907.0,...,292.5,29.019,51.0,52.0,55.0,55.0,200.0,200.0,200.0,200.0
143,40.982240,-86.385420,WHIN053-PULA005,2020-04-07T15:30:00Z,68.0,68.0,68.0,70.0,240.0,253.0,...,225.0,29.083,59.0,54.0,51.0,49.0,200.0,200.0,200.0,200.0
144,40.537220,-86.953420,WHIN054-WHIT007,2020-04-08T14:45:00Z,60.0,60.0,58.0,83.0,0.0,32767.0,...,45.0,29.034,58.0,57.0,56.0,52.0,200.0,200.0,200.0,200.0
145,40.586290,-87.436540,WHIN055-BENT006,2020-04-08T11:30:00Z,55.0,55.0,55.0,88.0,0.0,0.0,...,180.0,28.905,55.0,55.0,53.0,51.0,200.0,200.0,200.0,200.0
146,40.431340,-86.534640,WHIN056-CLIN004,2020-04-07T17:00:00Z,76.0,76.0,74.0,57.0,584.0,886.0,...,270.0,29.034,63.0,60.0,55.0,52.0,200.0,200.0,200.0,200.0
147,41.018650,-86.710100,WHIN057-PULA006,2020-04-01T14:45:00Z,50.0,50.0,49.0,73.0,478.0,547.0,...,67.5,29.362,55.0,54.0,52.0,51.0,200.0,200.0,200.0,200.0
149,40.590570,-86.391550,WHIN062-CARR009,2020-04-23T14:15:00Z,54.0,54.0,54.0,88.0,26.0,44.0,...,157.5,29.021,51.0,51.0,50.0,49.0,200.0,10.0,50.0,200.0
151,40.844360,-86.181730,WHIN059-CASS006,2020-05-06T12:30:00Z,41.0,43.0,41.0,75.0,223.0,265.0,...,22.5,29.202,56.0,47.0,48.0,51.0,0.0,0.0,0.0,0.0
153,40.385390,-87.510340,WHIN061-WARR006,2020-04-28T15:30:00Z,70.0,70.0,69.0,57.0,158.0,32767.0,...,202.5,29.194,60.0,61.0,57.0,56.0,0.0,0.0,0.0,0.0
155,40.701780,-86.706490,WHIN064-CARR010,2020-05-04T17:30:00Z,58.0,58.0,58.0,54.0,731.0,731.0,...,22.5,29.359,60.0,57.0,56.0,54.0,0.0,0.0,0.0,0.0
156,40.514320,-86.458560,WHIN065-CARR011,2020-05-06T16:45:00Z,53.0,53.0,53.0,43.0,1012.0,1014.0,...,337.5,29.445,52.0,55.0,52.0,51.0,0.0,0.0,1.0,0.0
157,40.548500,-87.124770,WHIN066-BENT006 EXT,2020-04-28T17:30:00Z,73.0,74.0,73.0,55.0,236.0,236.0,...,225.0,29.127,56.0,53.0,51.0,50.0,3.0,2.0,4.0,4.0
159,40.780490,-86.895760,WHIN068-WHIT008,2020-04-28T18:30:00Z,77.0,77.0,77.0,48.0,162.0,162.0,...,157.5,29.138,59.0,59.0,62.0,51.0,0.0,0.0,0.0,0.0
160,40.970610,-86.353040,WHIN069-CASS007,2020-05-06T14:30:00Z,47.0,48.0,47.0,52.0,654.0,654.0,...,22.5,29.244,54.0,50.0,49.0,50.0,0.0,0.0,0.0,0.0
163,40.161790,-87.352460,WHIN072-FOUN005,2020-06-26T16:45:00Z,92.0,92.0,89.0,56.0,249.0,32767.0,...,45.0,29.408,85.0,80.0,90.0,75.0,0.0,0.0,0.0,0.0
164,40.376340,-86.595910,WHIN073-CLIN006,2020-06-17T12:30:00Z,69.0,69.0,68.0,65.0,150.0,155.0,...,292.5,29.373,73.0,76.0,70.0,70.0,0.0,0.0,0.0,0.0
166,40.421240,-86.846420,Five Star Residence,2020-09-14T13:30:00Z,61.0,61.0,61.0,85.0,77.0,77.0,...,67.5,29.635,69.0,69.0,66.0,70.0,0.0,0.0,0.0,0.0
167,40.381160,-86.402690,WHIN075-CLIN007,2020-10-13T13:30:00Z,52.0,52.0,50.0,80.0,335.0,32767.0,...,247.5,29.263,54.0,57.0,58.0,60.0,0.0,0.0,0.0,0.0
168,40.480790,-87.206820,WHIN051E-BENT005,2021-01-13T19:00:00Z,70.0,71.0,70.0,26.0,0.0,0.0,...,202.5,29.825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,40.486975,-87.491418,WHIN074E-BENT007,2021-02-20T20:15:00Z,27.0,27.0,27.0,68.0,542.0,555.0,...,157.5,29.806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T20:15:00Z,31.0,31.0,31.0,62.0,582.0,599.0,...,157.5,30.342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,40.301560,-87.482480,WHIN009E-WARR001,2021-02-20T20:15:00Z,34.0,35.0,34.0,48.0,530.0,545.0,...,202.5,29.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,40.970062,-86.901372,WHIN071E-PULA009,2021-03-05T16:45:00Z,37.0,40.0,35.0,45.0,668.0,737.0,...,0.0,30.397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,40.149243,-86.737141,WHIN021E-MONT002,2021-03-08T15:45:00Z,53.0,54.0,53.0,61.0,NaN,32767.0,...,225.0,29.797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,40.384007,-87.316640,WHIN070E-WARR007,2021-02-21T01:00:00Z,21.0,22.0,21.0,75.0,0.0,0.0,...,90.0,29.732,33.0,34.0,35.0,35.0,8.0,6.0,5.0,4.0
179,40.386114,-87.101296,WHIN012E-WARR002,2021-02-21T01:00:00Z,23.0,24.0,23.0,70.0,0.0,0.0,...,135.0,30.469,32.0,33.0,33.0,34.0,34.0,18.0,7.0,4.0

### Explain the difference between the methodologies of using these two methods. We love getting your feedback. Which method do you prefer?
value_counts() outputs a count for all stations, while groupby() creates a new DF with station_id as the key. I prefer groupby() as it keeps the information more organized. However, if it was for a quick analysis or count, value_counts() would be more efficient.

## Question 2



Now count the total number of null values in the entire data frame myDF. (In other words, add up the values from all of the counts in part 2a.)

### Find out how many null records exist in myDF, within each individual column. (Your answer should specify, for each column, how many null records are in that column.)

In [6]:
myDF.isna().sum()

station_id                          0
latitude                            0
longitude                           0
name                                0
observation_time                    0
temperature                      4176
temperature_high                 4123
temperature_low                  4123
humidity                         4162
solar_radiation                 48104
solar_radiation_high            12828
rain                                0
rain_inches_last_hour               0
wind_speed_mph                   4032
wind_direction_degrees          95545
wind_gust_speed_mph                 0
wind_gust_direction_degrees     94216
pressure                            0
soil_temp_1                    114043
soil_temp_2                    114041
soil_temp_3                    114037
soil_temp_4                    114036
soil_moist_1                   114124
soil_moist_2                   114170
soil_moist_3                   114174
soil_moist_4                   114150
dtype: int64

### Now count the total number of null values in the entire data frame myDF. (In other words, add up the values from all of the counts in part 2a.)

In [7]:
total_na = 4176 + 4123 +4123 + 4162 + 48104 + 12828 + 4032 + 955545 + 94216 + 114043 + 114041 + 114037 + 114036 + 114124 + 114170 + 114174 + 114150
print(total_na)

2044084

### Drop rows with any null values in myDF. Save the resulting cleaned data set into a new DataFrame called myDF_cleaned.

In [8]:
myDF.shape

(1000000, 26)

In [9]:
myDF_cleaned = myDF.dropna()
myDF_cleaned

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,...,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
12823,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:15:00Z,52.0,52.0,52.0,94.0,31.0,...,225.0,29.805,46.0,44.0,44.0,44.0,7.0,14.0,11.0,9.0
12824,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:30:00Z,52.0,52.0,52.0,94.0,24.0,...,225.0,29.805,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12825,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:45:00Z,52.0,52.0,52.0,95.0,23.0,...,225.0,29.810,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12826,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:00:00Z,52.0,52.0,52.0,94.0,29.0,...,225.0,29.813,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12827,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:15:00Z,52.0,52.0,52.0,95.0,17.0,...,225.0,29.814,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973747,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:00:00Z,42.0,42.0,42.0,78.0,0.0,...,337.5,30.283,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973748,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:15:00Z,42.0,42.0,42.0,79.0,0.0,...,337.5,30.286,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973749,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:30:00Z,41.0,42.0,41.0,79.0,0.0,...,337.5,30.287,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973750,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:45:00Z,41.0,41.0,41.0,79.0,0.0,...,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973751,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T05:00:00Z,42.0,42.0,41.0,78.0,0.0,...,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0

### Just to make sure that you did this properly, check myDF_cleaned carefully: Are there any null values remaining in myDF_cleaned? (There should not be.) How many rows and columns are in myDF_cleaned?

In [10]:
myDF_cleaned.shape

(767725, 26)

## Question 3

### Go back to the original data frame myDF. Create a new data frame, by removing all rows from myDF in which the column temperature is a null value.

In [11]:
myDF.head

<bound method NDFrame.head of         station_id   latitude  longitude              name  \
0                1  40.938940 -86.474180   WHIN001-PULA001
1                1  40.938940 -86.474180   WHIN001-PULA001
2                1  40.938940 -86.474180   WHIN001-PULA001
3                1  40.938940 -86.474180   WHIN001-PULA001
4                1  40.938940 -86.474180   WHIN001-PULA001
...            ...        ...        ...               ...
999995         171  40.296799 -87.390285  WHIN038E-WARR004
999996         171  40.296799 -87.390285  WHIN038E-WARR004
999997         171  40.296799 -87.390285  WHIN038E-WARR004
999998         171  40.296799 -87.390285  WHIN038E-WARR004
999999         171  40.296799 -87.390285  WHIN038E-WARR004

            observation_time  temperature  temperature_high  temperature_low  \
0       2019-07-10T04:00:00Z         70.0              71.0             70.0
1       2019-07-10T04:15:00Z         69.0              70.0             69.0
2       2019-07-11T04:00:00Z         76.0              77.0             76.0
3       2019-07-11T04:15:00Z         76.0              76.0             76.0
4       2019-07-11T04:30:00Z         76.0              76.0             76.0
...                      ...          ...               ...              ...
999995  2021-07-10T06:30:00Z         64.0              64.0             64.0
999996  2021-07-10T06:45:00Z         64.0              64.0             64.0
999997  2021-07-10T07:00:00Z         64.0              64.0             64.0
999998  2021-07-10T07:15:00Z         64.0              64.0             64.0
999999  2021-07-10T07:30:00Z         64.0              64.0             63.0

        humidity  solar_radiation  ...  wind_gust_direction_degrees  pressure  \
0           83.0              NaN  ...                        247.5    30.050
1           84.0              NaN  ...                        247.5    30.040
2           76.0              NaN  ...                        202.5    29.890
3           77.0              NaN  ...                        202.5    29.880
4           77.0              NaN  ...                        202.5    29.880
...          ...              ...  ...                          ...       ...
999995      91.0              0.0  ...                          NaN    30.015
999996      90.0              0.0  ...                         90.0    30.017
999997      91.0              0.0  ...                         67.5    30.016
999998      91.0              0.0  ...                         67.5    30.010
999999      91.0              0.0  ...                         67.5    29.996

        soil_temp_1  soil_temp_2  soil_temp_3  soil_temp_4  soil_moist_1  \
0              77.0         78.0         76.0         74.0          24.0
1              76.0         78.0         76.0         74.0          24.0
2              80.0         80.0         78.0         75.0          31.0
3              80.0         80.0         78.0         75.0          31.0
4              80.0         80.0         78.0         75.0          32.0
...             ...          ...          ...          ...           ...
999995          NaN          NaN          NaN          NaN           NaN
999996          NaN          NaN          NaN          NaN           NaN
999997          NaN          NaN          NaN          NaN           NaN
999998          NaN          NaN          NaN          NaN           NaN
999999          NaN          NaN          NaN          NaN           NaN

        soil_moist_2  soil_moist_3  soil_moist_4
0               24.0          10.0           9.0
1               25.0          10.0           9.0
2               30.0          12.0          10.0
3               31.0          12.0          10.0
4               31.0          12.0          10.0
...              ...           ...           ...
999995           NaN           NaN           NaN
999996           NaN           NaN           NaN
999997           NaN           NaN           NaN
999998           NaN           NaN           NaN
999999           NaN           NaN           NaN

[1000000 rows x 26 columns]>

In [12]:
myDF["temperature"] = myDF["temperature"].dropna()

### Combine the columns latitude and longitude into a new column called location with '_' in between.

In [13]:
myDF['location'] = myDF['latitude'].astype(str) + '_' + myDF['longitude'].astype(str)
myDF

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,...,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4,location
0,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,...,30.050,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0,40.93894_-86.47418
1,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,...,30.040,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0,40.93894_-86.47418
2,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,...,29.890,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0,40.93894_-86.47418
3,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,...,29.880,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0,40.93894_-86.47418
4,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,...,29.880,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0,40.93894_-86.47418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:30:00Z,64.0,64.0,64.0,91.0,0.0,...,30.015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.2967994865571_-87.3902853950858
999996,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:45:00Z,64.0,64.0,64.0,90.0,0.0,...,30.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.2967994865571_-87.3902853950858
999997,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:00:00Z,64.0,64.0,64.0,91.0,0.0,...,30.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.2967994865571_-87.3902853950858
999998,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:15:00Z,64.0,64.0,64.0,91.0,0.0,...,30.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.2967994865571_-87.3902853950858
999999,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:30:00Z,64.0,64.0,63.0,91.0,0.0,...,29.996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.2967994865571_-87.3902853950858

### Grouping the data by the location column, find the average temperature for each location, and print your results: Each line that you print should have 1 location and 1 average temperature for that location.

In [20]:
myDF.groupby('location')['temperature'].mean()

location
40.10483_-86.86619                    56.057495
40.1492432088387_-86.7371410131454    61.413324
40.16179_-87.35246                    54.052897
40.2709571472446_-87.1486035394257    49.803342
40.2967994865571_-87.3902853950858    57.855233
40.30156_-87.48248                    58.889855
40.37634_-86.59591                    54.794076
40.38116_-86.40269                    47.765668
40.3840069271445_-87.31664031744      59.552215
40.38539_-87.51034                    55.115662
40.3861140862113_-87.1012964844704    59.383360
40.42124_-86.84642                    50.742410
40.43134_-86.53464                    55.081819
40.48079_-87.20682                    51.730032
40.4869749155437_-87.4914180859923    58.971553
40.51432_-86.45856                    55.183031
40.53722_-86.95342                    55.070667
40.5485_-87.12477                     54.898998
40.58629_-87.43654                    54.676701
40.59057_-86.39155                    55.307808
40.70178_-86.70649                    55.482287
40.78049_-86.89576                    54.791890
40.84436_-86.18173                    54.942505
40.93894_-86.47418                    49.883742
40.9700622558594_-86.9013715815608    59.919768
40.97061_-86.35304                    55.292530
40.98224_-86.38542                    54.206106
41.01865_-86.7101                     53.836086
Name: temperature, dtype: float64

## Question 4

Wrap your work from Question 3 into a function. This function should take a data frame as a parameter, and should drop records with null value in the data frame’s temperature column. The function should also create a new location column, and should calculate the average temperature (grouped by location). The function should return the Series of average temperatures (grouped by location).

In [26]:
def get_avg_temp (myDF):
    myDF = pd.read_csv("/anvil/projects/tdm/data/whin/weather.csv")
    myDF_cleaned = myDF.dropna()
    myDF_cleaned['location'] = myDF_cleaned['latitude'].astype(str) + '_' + myDF_cleaned['longitude'].astype(str)
    avg_temp = myDF_cleaned.groupby('location')['temperature'].mean()
    return avg_temp

In [27]:
get_avg_temp(myDF)

/tmp/ipykernel_2974776/525689122.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDF_cleaned['location'] = myDF_cleaned['latitude'].astype(str) + '_' + myDF_cleaned['longitude'].astype(str)

location
40.10483_-86.86619                    55.795827
40.16179_-87.35246                    53.826035
40.2709571472446_-87.1486035394257    49.977179
40.37634_-86.59591                    54.916286
40.38116_-86.40269                    47.996461
40.3840069271445_-87.31664031744      44.836799
40.38539_-87.51034                    55.435129
40.3861140862113_-87.1012964844704    42.005992
40.42124_-86.84642                    50.878671
40.43134_-86.53464                    55.102383
40.51432_-86.45856                    55.400226
40.53722_-86.95342                    57.639716
40.5485_-87.12477                     54.867862
40.58629_-87.43654                    55.085078
40.59057_-86.39155                    55.369460
40.70178_-86.70649                    55.642011
40.78049_-86.89576                    55.032875
40.84436_-86.18173                    55.298587
40.93894_-86.47418                    50.700275
40.97061_-86.35304                    55.632911
40.98224_-86.38542                    54.493940
41.01865_-86.7101                     54.675659
Name: temperature, dtype: float64

## Question 5

Now considering the column called wind_gust_speed_mph (instead of temperature), do the work from questions 3 and 4 again.

Which location has the largest average value of the wind_gust_speed_mph

In [30]:
myDF["wind_gust_speed_mph"] = myDF["wind_gust_speed_mph"].dropna()

In [32]:
myDF['location'] = myDF['latitude'].astype(str) + '_' + myDF['longitude'].astype(str)
myDF.groupby('location')['wind_gust_speed_mph'].mean()

location
40.10483_-86.86619                    10.186783
40.1492432088387_-86.7371410131454    10.136323
40.16179_-87.35246                     9.026960
40.2709571472446_-87.1486035394257     9.993939
40.2967994865571_-87.3902853950858    11.560288
40.30156_-87.48248                    10.146300
40.37634_-86.59591                    10.174628
40.38116_-86.40269                    12.850781
40.3840069271445_-87.31664031744       6.184488
40.38539_-87.51034                    11.075690
40.3861140862113_-87.1012964844704     7.812415
40.42124_-86.84642                     5.973414
40.43134_-86.53464                    11.226047
40.48079_-87.20682                     6.290135
40.4869749155437_-87.4914180859923    11.720362
40.51432_-86.45856                    10.181839
40.53722_-86.95342                    11.794791
40.5485_-87.12477                     10.516033
40.58629_-87.43654                    11.681777
40.59057_-86.39155                    10.055651
40.70178_-86.70649                     9.843719
40.78049_-86.89576                    10.852191
40.84436_-86.18173                    10.285053
40.93894_-86.47418                     9.944437
40.9700622558594_-86.9013715815608    11.544695
40.97061_-86.35304                    10.564448
40.98224_-86.38542                    10.964359
41.01865_-86.7101                      8.975526
Name: wind_gust_speed_mph, dtype: float64

In [36]:
def get_avg_wind_mph (myDF):
    myDF = pd.read_csv("/anvil/projects/tdm/data/whin/weather.csv")
    myDF_cleaned = myDF.dropna()
    myDF_cleaned['location'] = myDF_cleaned['latitude'].astype(str) + '_' + myDF_cleaned['longitude'].astype(str)
    avg_mph = myDF_cleaned.groupby('location')['wind_gust_speed_mph'].mean()
    return avg_mph

get_avg_wind_mph(myDF)

/tmp/ipykernel_2974776/497765146.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myDF_cleaned['location'] = myDF_cleaned['latitude'].astype(str) + '_' + myDF_cleaned['longitude'].astype(str)

13.125009616124316

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.